site_name: Vishal Gakhare
site_url: https://vishalgakhare.github.io/theone/
site_author: Vishal Gakhare
site_description: >-
  The second brain - digial garden - for all things I read, learn and think.

# Repository
repo_name: vishalgakhare/theone
repo_url: https://github.com/vishalgakhare/theone.git

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Customization
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vishalgakhare
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/vishalgakhare/
